// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeLI0Dt1LwrLdreOFua3gR8s1hKMEv_ls',
    appId: '1:895702498929:web:3d13b17918d707f08565d0',
    messagingSenderId: '895702498929',
    projectId: 'controle-de-gastos-9d720',
    authDomain: 'controle-de-gastos-9d720.firebaseapp.com',
    storageBucket: 'controle-de-gastos-9d720.firebasestorage.app',
    measurementId: 'G-0EPQFBBJSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlpSwC7PezjDDmohKAZoIpH1f14jY7UxI',
    appId: '1:895702498929:android:3a7657ca293f081c8565d0',
    messagingSenderId: '895702498929',
    projectId: 'controle-de-gastos-9d720',
    storageBucket: 'controle-de-gastos-9d720.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxmdQeagQfYxJZlNKNhGVnSCciNOnPtxY',
    appId: '1:895702498929:ios:579692d4513b83e08565d0',
    messagingSenderId: '895702498929',
    projectId: 'controle-de-gastos-9d720',
    storageBucket: 'controle-de-gastos-9d720.firebasestorage.app',
    iosBundleId: 'com.example.controleGastos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxmdQeagQfYxJZlNKNhGVnSCciNOnPtxY',
    appId: '1:895702498929:ios:579692d4513b83e08565d0',
    messagingSenderId: '895702498929',
    projectId: 'controle-de-gastos-9d720',
    storageBucket: 'controle-de-gastos-9d720.firebasestorage.app',
    iosBundleId: 'com.example.controleGastos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeLI0Dt1LwrLdreOFua3gR8s1hKMEv_ls',
    appId: '1:895702498929:web:5918d278e38abff08565d0',
    messagingSenderId: '895702498929',
    projectId: 'controle-de-gastos-9d720',
    authDomain: 'controle-de-gastos-9d720.firebaseapp.com',
    storageBucket: 'controle-de-gastos-9d720.firebasestorage.app',
    measurementId: 'G-HZY3527TXM',
  );
}
